version: '3'
services:

    mysql:
        image: mysql:5.7
        container_name: db-for-go
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
        environment:
            MYSQL_ROOT_USER: "sandauser"
            MYSQL_ROOT_PASSWORD: "sandatodo"
            MYSQL_DATABASE: "sandaapp"
            MYSQL_USER: "sandauser"
            MYSQL_PASSWORD: "sandatodo"
            TZ: 'Asia/Tokyo'
        ports:
            - "3306:3306"
        volumes:
            - db-volume-sanda:/var/lib/mysql

volumes:
    db-volume-sanda: